# Generated by Django 4.0.1 on 2022-01-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='qq',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
